---
title: "DAG"
format: html
---

```{r}

library(ggdag)
library(ggplot2)

```

# DAG
```{r}

survival_dag = dagify(Survival ~ EMT_Score + Disease_Stage + Age + Immune_Infiltrate + Treatment + Sex,
                      EMT_Score ~ Sample_Purity + CAF_Infiltrate,
                      Treatment ~ Disease_Stage + Sample_Collection_Year,
                      Immune_Infiltrate ~ Cancer_Antigens,
                      Tissue_Rollup ~ Disease_Stage,
                      Cancer_Antigens ~ Disease_Stage,
                      Sample_Purity ~ Tissue_Rollup + Immune_Infiltrate + CAF_Infiltrate,
                      labels = c("Survival" = "Survival",
                                 "EMT_Score" = "EMT\nScore",
                                 "Disease_Stage" = "Disease Stage",
                                 "Age" = "Patient\nAge",
                                 "Tissue_Rollup" = "Sample Tissue\nSource",
                                 "Immune_Infiltrate" = "Immune\nInfiltrate",
                                 "Sample_Collection_Year" = "Year Sample\nCollected",
                                 "Treatment" = "Treatment(s)\nReceived",
                                 "Sex" = "Patient\nSex",
                                 "CAF_Infiltrate" = "Cancer Associated\nFibroblasts",
                                 "Cancer_Antigens" = "Cancer Antigen\nExpression",
                                 "Genetic_Programs" = "Gene Expression\nPrograms",
                                 "Sample_Purity" = "Sample Tumor Fraction"),
                      exposure = "EMT_Score",
                      outcome = "Survival")


```

# DAG plot
```{r, height = 1200, width = 1200, res = 200}

ggdag(survival_dag, 
      text = FALSE, 
      use_labels = "label", 
      node = TRUE) +
    theme_dag()

```


## Save DAG plot
```{r}

png(file = "../outputs/plots/DAG.png", bg = "white", height = 1000, width = 1000, res = 120)
ggdag(survival_dag, text = FALSE, use_labels = "label") +
    theme_dag()
dev.off()

```

# Backdoor adjustment paths
```{r}

#Immune infiltrate
ggdag_adjustment_set(survival_dag,
                     exposure = c("Immune_Infiltrate"),
                     outcome = "Survival",
                     text = FALSE,
                     text_col = "black",
                     use_labels = "label",
                     shadow = TRUE) +
  theme_dag_blank() +
  ggtitle("Immune Infiltrate")

#Disease Stage
ggdag_adjustment_set(survival_dag,
                     exposure = c("Disease_Stage"),
                     outcome = "Survival",
                     text_col = "black",
                     text = FALSE,
                     use_labels = "label") +
  theme_dag_blank() +
  ggtitle("Disease Stage")

#EMT Score
ggdag_adjustment_set(survival_dag,
                     exposure = c("EMT_Score"),
                     outcome = "Survival",
                     text_col = "black",
                     text = FALSE,
                     use_labels = "label") +
  theme_dag_blank() +
  ggtitle("Epithelial-Mesenchymal Score")

#Age
ggdag_adjustment_set(survival_dag,
                     exposure = c("Age"),
                     outcome = "Survival",
                     text_col = "black",
                     text = FALSE,
                     use_labels = "label") +
  theme_dag_blank() +
  ggtitle("Patient Age")

#Sex
ggdag_adjustment_set(survival_dag,
                     exposure = c("Sex"),
                     outcome = "Survival",
                     text_col = "black",
                     text = FALSE,
                     use_labels = "label") +
  theme_dag_blank() +
  ggtitle("Patient Sex")



```

# Paths

ggdag_paths(survival_dag,
            from = "Immune_Infiltrate",
            to = "Survival") 

#Adjustment sets